apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{componentName}}-deployment 
  namespace: {{namespace}}
spec: 
  replicas: 1 
  selector: 
     matchLabels: 
       app: {{componentName}} 
  template: 
    metadata: 
      labels: 
        app: {{componentName}} 
    spec: 
      terminationGracePeriodSeconds: 30 
      hostname: mssqlinst 
      securityContext: 
        fsGroup: 10001 
      containers: 
      - name: {{componentName}} 
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
        - containerPort: 1433 
        env: 
        - name: MSSQL_PID 
          value: "Developer" 
        - name: ACCEPT_EULA 
          value: "Y" 
        - name: SA_PASSWORD 
          valueFrom: 
            secretKeyRef: 
              name: mssql-server 
              key: SA_PASSWORD 
        volumeMounts: 
        - name: {{componentName}}-data-pv  
          mountPath: /var/opt/mssql 
      volumes: 
      - name: {{componentName}}-data-pv 
        persistentVolumeClaim: 
          claimName: mssql-server-data-pvc