apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ui
  namespace: {{namespace}}
  labels:
    app: docker-registry-ui
    release: docker-registry-ui
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Access-Control-Allow-Origin: $http_origin";
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, 
        OPTIONS, DELETE, PATCH
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{componentName}}-ui.{{baseDomain}}
  rules:
    - host: {{componentName}}-ui.{{baseDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry-docker-registry-ui-user-interface
                port:
                  number: 80