name: Changelog
on: workflow_dispatch 

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "âœï¸ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# ğŸ“‘ Changelog"
          breakingLabel: '### ğŸ’¥ Breaking'
          enhancementLabel: '### ğŸš€ Enhancements'
          bugsLabel: '### ğŸ› Bug fixes'
          stripGeneratorNotice: true
          sinceTag: v0.8.6
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md   
      - name: Get CHANGELOG
        id: vars
        run: echo ::set-output name=changelog::$(cat ./CHANGELOG.md | sed '/\*\*/q' | sed '$d')
      - name: Send CHANGELOG to Discord
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ${{ steps.vars.outputs.changelog }}
