name: Changelog
on: workflow_dispatch 

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "‚úèÔ∏è Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# üìë Changelog"
          breakingLabel: '### üí• Breaking'
          enhancementLabel: '### üöÄ Enhancements'
          bugsLabel: '### üêõ Bug fixes'
          stripGeneratorNotice: true
          sinceTag: v0.8.6
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md   
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          echo ::set-output name=changelog::$(cat ./CHANGELOG.md | awk '/###/ {exit} {print}' | awk '{printf "%s\\n", $0}')
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          DISCORD_MULTILINE: 1
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}"
