name: Changelog
on: workflow_dispatch 

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "‚úèÔ∏è Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# üìë Changelog"
          breakingLabel: '### Breaking'
          enhancementLabel: '### Enhancements'
          bugsLabel: '### Bug fixes'
          stripGeneratorNotice: true
          release-url: https://github.com/Accenture/kx.as.code/releases/tag/v0.8.9
          sinceTag: v0.8.6
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md   
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          CHANGELOG=$(cat ./CHANGELOG.md | awk '/###/ {exit} {print}')
          if [ ! -f ./HISTORY.md ]; then
            touch ./HISTORY.md
          fi
          if [ -z $(cat ./HISTORY.md | grep "v0.8.9") ]; then
            cat ./CHANGELOG.md | tee -a ./HISTORY.md
          fi
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$(echo $CHANGELOG)
      - name: Archive-HISTORY.md
        uses: actions/upload-artifact@v3
        with:
          name: HISTORY.md
          path: ./HISTORY.md
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}\n"
